CREATE DATABASE ng_games_db;
USE ng_games_db;
CREATE TABLE game(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tittle VARCHAR(180),
    description VARCHAR(255),
    image VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE game;